"""Project constants and shared paths."""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
CONFIG_DIR = PROJECT_ROOT / "configs"
DEFAULT_CONFIG_PATH = CONFIG_DIR / "default.yaml"
DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
DATA_CACHE_DIR = DATA_DIR / "cache"
RUNS_DIR = PROJECT_ROOT / "runs"

DEFAULT_TIMEFRAME = "1h"
OHLCV_COLUMNS = ["timestamp", "open", "high", "low", "close", "volume"]
DEFAULT_WALKFORWARD_FORWARD_DAYS = 7
DEFAULT_WALKFORWARD_NUM_WINDOWS = 8
DEFAULT_WALKFORWARD_MIN_USABLE_WINDOWS = 3
DEFAULT_WALKFORWARD_MIN_FORWARD_TRADES = 10
DEFAULT_WALKFORWARD_MIN_FORWARD_EXPOSURE = 0.01
DEFAULT_WALKFORWARD_PF_CLIP_MAX = 5.0
DEFAULT_WALKFORWARD_STABILITY_METRIC = "exp_lcb"
